project 'Smack.xcodeproj'

 source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '9.0'

target 'Smack' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

# Pods for Smack
#pod 'Alamofire', '~> 4.0'
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
#pod 'SwiftyJSON' , '~> 3.1'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
#pod 'Socket.IO-Client-Swift', '~> 11.1.3'
pod 'Socket.IO-Client-Swift', :git => 'https://github.com/socketio/socket.io-client-swift.git', :branch => '1.0-swift4'
end
